### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by antony999k** [antony999k/MoodTrackerApi#1]
/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/mongoose/lib/connection.js:579
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/mongoose/lib/connection.js:579:11)
    at Mongoose.connect (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/mongoose/lib/index.js:333:15)
    at Object.<anonymous> (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/app.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at Object.<anonymous> (/Users/antony999k/Documents/ITESM/DesarrolloWeb/MoodTrackerAPI/node_modules/@babel/node/lib/_babel-node.js:180:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by luisbarajasp** [comment]
You needed the updated .env
